import type { Metadata } from "next";
import "../../../globals.css";
import { redirect } from "next/navigation";
import { getUser } from "@/lib/auth";


export const metadata: Metadata = {
  title: "Log-in",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {session,user} = await getUser();
  if(session && user.role === "superadmin"){
      return redirect('/dashboard');
  }
  return (
    
      <div
        >
        {children}
      </div>
 
  );
}
